# Generated by Django 5.1.7 on 2025-04-20 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CPT Code')),
                ('description', models.TextField(verbose_name='Procedure Description')),
            ],
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ICD-10 Code')),
                ('description', models.TextField(verbose_name='Diagnosis Description')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='-', max_length=255)),
                ('age', models.CharField(default='-', max_length=20)),
                ('gender', models.CharField(default='-', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mrn', models.CharField(default='-', max_length=50)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, upload_to='medical_reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.TextField(default='-')),
                ('clinical_indication', models.TextField(default='-')),
                ('findings', models.TextField(default='-')),
                ('impression', models.TextField(default='-')),
                ('processing_log', models.TextField(blank=True, help_text='Any processing errors or notes')),
                ('cpt_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.cptcode', verbose_name='Associated CPT Code')),
                ('icd10_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coding.icd10code', verbose_name='Associated ICD-10 Code')),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-date_of_service'],
            },
        ),
    ]
